name: 'Check YouTube and Post to Bsky'

on:
  schedule:
    - cron: '0 15 * * FRI'

jobs:
  check_and_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run check and post script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: node src/checkAndPost.js
